-- Mini Anveshana PostgreSQL schema for Supabase.
-- Production migration only. Do not add development/demo data here.

CREATE TABLE IF NOT EXISTS event_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  event_name TEXT NOT NULL DEFAULT 'Mini Anveshana',
  tagline TEXT NOT NULL DEFAULT 'Bring Your Idea. Build Your Solution.',
  event_date TEXT,
  venue TEXT,
  registration_deadline TEXT,
  project_deadline TEXT,
  team_size_min INTEGER NOT NULL DEFAULT 2,
  team_size_max INTEGER NOT NULL DEFAULT 4,
  contact_email TEXT,
  registration_open INTEGER NOT NULL DEFAULT 1,
  late_submission_allowed INTEGER NOT NULL DEFAULT 0,
  results_published INTEGER NOT NULL DEFAULT 0,
  certificates_enabled INTEGER NOT NULL DEFAULT 0,
  module_projects_public INTEGER NOT NULL DEFAULT 1,
  module_schedule_public INTEGER NOT NULL DEFAULT 1,
  scoring_formula TEXT NOT NULL DEFAULT 'average',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO event_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS evaluation_criteria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  max_score INTEGER NOT NULL DEFAULT 20,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('student', 'organizer', 'evaluator', 'super_admin')),
  phone TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS colleges (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  university TEXT,
  city TEXT,
  state TEXT,
  coordinator_name TEXT,
  coordinator_email TEXT,
  coordinator_phone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(name, city)
);

CREATE TABLE IF NOT EXISTS teams (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_id TEXT NOT NULL UNIQUE,
  team_name TEXT NOT NULL,
  college_id INTEGER NOT NULL REFERENCES colleges(id),
  department TEXT,
  leader_user_id INTEGER REFERENCES users(id),
  leader_name TEXT NOT NULL,
  leader_email TEXT NOT NULL,
  leader_usn TEXT,
  leader_phone TEXT,
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('draft', 'registered', 'submitted', 'under_review', 'approved', 'rejected')),
  rejection_reason TEXT,
  qr_token TEXT NOT NULL UNIQUE,
  checked_in INTEGER NOT NULL DEFAULT 0,
  checked_in_at TIMESTAMPTZ,
  checked_in_by INTEGER REFERENCES users(id),
  consent_confirmed INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_teams_college ON teams(college_id);
CREATE INDEX IF NOT EXISTS idx_teams_status ON teams(status);
CREATE INDEX IF NOT EXISTS idx_teams_qr ON teams(qr_token);

CREATE TABLE IF NOT EXISTS team_members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id),
  full_name TEXT NOT NULL,
  email TEXT,
  usn TEXT,
  department TEXT,
  year TEXT,
  is_leader INTEGER NOT NULL DEFAULT 0,
  invitation_status TEXT NOT NULL DEFAULT 'accepted' CHECK (invitation_status IN ('pending', 'accepted', 'declined')),
  invitation_token TEXT UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_members_team ON team_members(team_id);

CREATE TABLE IF NOT EXISTS faculty_coordinators (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  department TEXT,
  email TEXT,
  phone TEXT
);

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id INTEGER NOT NULL UNIQUE REFERENCES teams(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id),
  title TEXT NOT NULL,
  problem_statement TEXT,
  solution_description TEXT,
  features TEXT,
  technologies TEXT,
  architecture TEXT,
  expected_outcome TEXT,
  future_scope TEXT,
  demo_video_url TEXT,
  github_url TEXT,
  status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'draft', 'submitted', 'reviewed')),
  is_approved_public INTEGER NOT NULL DEFAULT 0,
  final_score REAL,
  final_rank INTEGER,
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_projects_category ON projects(category_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);

CREATE TABLE IF NOT EXISTS project_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  file_type TEXT NOT NULL CHECK (file_type IN ('abstract', 'presentation', 'image', 'other')),
  file_name TEXT NOT NULL,
  r2_key TEXT NOT NULL,
  content_type TEXT,
  size_bytes INTEGER,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_files_project ON project_files(project_id);

CREATE TABLE IF NOT EXISTS event_schedule (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_time TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  category_id INTEGER REFERENCES categories(id),
  stage TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS announcements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal', 'important', 'urgent')),
  published_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ,
  created_by INTEGER REFERENCES users(id),
  is_active INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_announce_active ON announcements(is_active);

CREATE TABLE IF NOT EXISTS evaluators (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  organization TEXT,
  expertise TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS evaluator_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluator_id INTEGER NOT NULL REFERENCES evaluators(id) ON DELETE CASCADE,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  assigned_by INTEGER REFERENCES users(id),
  UNIQUE(evaluator_id, project_id)
);
CREATE INDEX IF NOT EXISTS idx_assign_evaluator ON evaluator_assignments(evaluator_id);
CREATE INDEX IF NOT EXISTS idx_assign_project ON evaluator_assignments(project_id);

CREATE TABLE IF NOT EXISTS evaluations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id INTEGER NOT NULL UNIQUE REFERENCES evaluator_assignments(id) ON DELETE CASCADE,
  evaluator_id INTEGER NOT NULL REFERENCES evaluators(id),
  project_id INTEGER NOT NULL REFERENCES projects(id),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed')),
  total_score REAL,
  strengths TEXT,
  suggestions TEXT,
  comments TEXT,
  submitted_at TIMESTAMPTZ,
  reopened_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_eval_project ON evaluations(project_id);
CREATE INDEX IF NOT EXISTS idx_eval_status ON evaluations(status);

CREATE TABLE IF NOT EXISTS evaluation_scores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluation_id INTEGER NOT NULL REFERENCES evaluations(id) ON DELETE CASCADE,
  criterion_id INTEGER NOT NULL REFERENCES evaluation_criteria(id),
  score REAL NOT NULL DEFAULT 0,
  UNIQUE(evaluation_id, criterion_id)
);

CREATE TABLE IF NOT EXISTS checkins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  scanned_by INTEGER REFERENCES users(id),
  checkin_time TIMESTAMPTZ NOT NULL DEFAULT now(),
  result TEXT NOT NULL DEFAULT 'success' CHECK (result IN ('success', 'duplicate', 'invalid'))
);
CREATE INDEX IF NOT EXISTS idx_checkins_team ON checkins(team_id);

CREATE TABLE IF NOT EXISTS certificates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  certificate_id TEXT NOT NULL UNIQUE,
  team_id INTEGER NOT NULL REFERENCES teams(id),
  member_id INTEGER REFERENCES team_members(id),
  recipient_name TEXT NOT NULL,
  cert_type TEXT NOT NULL DEFAULT 'participation' CHECK (cert_type IN ('participation', 'winner', 'runner_up', 'special_mention')),
  issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_available INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_cert_team ON certificates(team_id);

CREATE TABLE IF NOT EXISTS certificate_verifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  certificate_id TEXT NOT NULL,
  verified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ip_hint TEXT
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  action TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
