-- =========================================================
-- DEVELOPMENT / DEMO SEED DATA — DO NOT RUN IN PRODUCTION
-- Apply only with: npm run db:seed  (local/dev database)
-- =========================================================

-- Categories
INSERT INTO categories (name, slug, description, sort_order) VALUES
  ('Healthcare & Wellness', 'healthcare', 'Solutions that improve health outcomes and patient care.', 1),
  ('Sustainability & Environment', 'sustainability', 'Projects tackling climate, waste, and resource challenges.', 2),
  ('Education & Learning', 'education', 'Tools that make learning more accessible and effective.', 3),
  ('Smart Agriculture', 'agriculture', 'Technology-driven solutions for farming and food systems.', 4),
  ('AI & Data Applications', 'ai-data', 'Applied machine learning and data-driven products.', 5),
  ('Civic & Community Tech', 'civic-tech', 'Solutions for local governance, safety, and community needs.', 6);

-- Evaluation criteria (configurable, sums to 100)
INSERT INTO evaluation_criteria (name, description, max_score, sort_order) VALUES
  ('Innovation', 'Originality and creativity of the idea', 20, 1),
  ('Problem Relevance', 'How well the problem is understood and how relevant it is', 20, 2),
  ('Technical Implementation', 'Quality and depth of the technical build', 20, 3),
  ('Impact', 'Potential real-world impact and usefulness', 20, 4),
  ('Presentation', 'Clarity of communication and demo quality', 20, 5);

-- Demo colleges
INSERT INTO colleges (name, university, city, state, coordinator_name, coordinator_email, coordinator_phone) VALUES
  ('Sri Vidya Institute of Technology', 'Visvesvaraya Technological University', 'Bengaluru', 'Karnataka', 'Dr. Ramesh Kumar', 'ramesh.k@svit.edu.in', '9800011122'),
  ('Nalanda College of Engineering', 'Anna University', 'Chennai', 'Tamil Nadu', 'Dr. Priya Menon', 'priya.menon@nalanda.edu.in', '9800022233'),
  ('Greenfield Institute of Technology', 'JNTU', 'Hyderabad', 'Telangana', 'Prof. Arvind Rao', 'arvind.rao@greenfield.edu.in', '9800033344');

-- Demo users (password for ALL demo accounts: "Anveshana@123")
-- password_hash values are PBKDF2 placeholders generated by the app's hashPassword() at seed time via API,
-- so this file only creates the account shells; run `POST /api/dev/seed-users` in dev mode to attach real hashes.

-- Demo announcement
INSERT INTO announcements (title, message, priority, created_by) VALUES
  ('Welcome to Mini Anveshana', 'Registrations are now open. Please read the rules page before submitting your team.', 'normal', NULL);

-- Demo schedule
INSERT INTO event_schedule (event_time, title, description, location, stage, sort_order) VALUES
  ('09:00 AM', 'Registration Desk Opens', 'Team check-in and badge collection', 'Main Lobby', 'Day 1', 1),
  ('10:00 AM', 'Inauguration', 'Opening ceremony and welcome address', 'Main Auditorium', 'Day 1', 2),
  ('11:00 AM', 'Project Setup', 'Teams set up their project stalls', 'Exhibition Hall', 'Day 1', 3),
  ('12:00 PM', 'Evaluation Round 1', 'Evaluators begin project reviews', 'Exhibition Hall', 'Day 1', 4),
  ('02:00 PM', 'Lunch Break', '', 'Cafeteria', 'Day 1', 5),
  ('03:00 PM', 'Evaluation Round 2', 'Final evaluation round', 'Exhibition Hall', 'Day 1', 6),
  ('05:00 PM', 'Results & Closing', 'Announcement of results and closing ceremony', 'Main Auditorium', 'Day 1', 7);
